language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - curl -Ls https://raw.githubusercontent.com/unb-libraries/dockworker/3.x/scripts/travis/init.sh | bash
  - composer install

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH

notifications:
  slack:
    rooms:
      secure: wX67PhlrBs9av+rARIN0lEDbqz2r+r4XoldGaBZoLDg3ExhZSTnG0eRUAJSunuf7GT2dwBYxXceh30s/2nL2B8yIhBcGLfFQRwGibgc2ItXd+CFoIrfcvpvE/5pJYpWLxHfW4j6/ozH1wFi/p1P6aUP9st9Fz1qQjM1xE3vdq7rxp6MsD+yFLTho/OIGxjbGjcm57Q2Y/yDzeo0FR+uM996YdbjwWgg+nf7287QGNHVFdSaYp9uwC4oyeFp1obsT2yX1aSFcyTiYTa2PXgjfOXCGD2dSZdn2PdBAIV8VZK6I+psgR8B2toOE+dUOfrf/X5Qe3KuP9IOIak9/9txng2jDBh62EzXetpoeKG5LpKZIXDo+s02mMqJ7Wbtp+SdJ7QmAWZxN8SYfQH546sSs8IKC1RBG4TlbigKz+wokduLNdHuW10qDD03YBR2RBV9fOMSfuZoo67LACs5hI2+Wds+PmJYvCv0ofLmUPHHR5k/XG8jNfBvoK0+Q0I7l4gQDnvY4OXfXHvFlcH8d494Ukwa5Nv1as8FUfZgnqbcUDMzMdTQjP/yaqTTN7bRp0VsjB78AR+/ls4vEJAYPU7MGfKpMduxiQk6V+fd8Dc6xxytKIJphF0zI9UhaJLDVL7Gy6LXeWrbhyrv0wMvE5o9jh0qTWRoypRHXWaa4lmTAdIc=
    on_start: always
    on_success: always
